{% set name = "pypinyin" %}
{% set version = "0.50.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypinyin-{{ version }}.tar.gz
  sha256: 72e77c4b9b78bad102aca5fefccebdb23439b02717c626039be14a78643980fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pypinyin = pypinyin.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pypinyin
    - pypinyin.contrib
    - pypinyin.seg
    - pypinyin.style
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mozillazg/python-pinyin
  summary: Converts Chinese idiograms to Pinyin romanization.
  doc_url: https://github.com/mozillazg/python-pinyin/blob/master/README_en.rst
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
