{% set name = "pypinyin" %}
{% set version = "0.53.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypinyin-{{ version }}.tar.gz
  sha256: a2d39ddc2bd31b55897bbb10d2e11a0c4d399988a97c00ad489c151afd9b106d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pypinyin = pypinyin.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pypinyin
    - pypinyin.contrib
    - pypinyin.seg
    - pypinyin.style
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mozillazg/python-pinyin
  summary: Converts Chinese idiograms to Pinyin romanization.
  doc_url: https://github.com/mozillazg/python-pinyin/blob/master/README_en.rst
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
