{% set name = "pypinyin" %}
{% set version = "0.44.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypinyin-{{ version }}.tar.gz
  sha256: 007b26cb945b96de41041e15a48161407dec36de132f08e23dfa6ec7e3624033

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pypinyin = pypinyin.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pypinyin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mozillazg/python-pinyin
  summary: Converts Chinese idiograms to Pinyin romanization.
  doc_url: https://github.com/mozillazg/python-pinyin/blob/master/README_en.rst
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
